#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hompage:
    path: /
    controller: App\Controller\DefaultController::homepage

add_product:
    path: /add/product
    controller: App\Controller\ProductController::addProduct
    
add_user:
    path: /sign/up
    controller: App\Controller\UserController::addUser

user_activate:
    path: /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'
