#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hompage:
    path: /
    controller: App\Controller\DefaultController::homepage
    
hompage_translation:
    path: /{_locale}
    controller: App\Controller\DefaultController::homepage
    requirements:
        _locale: 'en|fr'
 
add_product:
    path: /{_locale}/add/product
    controller: App\Controller\ProductController::addProduct
    requirements:
        _locale: 'en|fr'

detail_product:
    path: /{_locale}/detail/product/{id}
    controller: App\Controller\ProductController::detailProduct
    requirements:
        _locale: 'en|fr'
        
display_product:
    path: /{_locale}/display/product
    controller: App\Controller\ProductController::displayProduct
    requirements:
        _locale: 'en|fr'
        
username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameExist
    methods: ['POST']

login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    
logout:
    path: /logout



add_user:
    path: /{_locale} /sign/up
    controller: App\Controller\UserController::addUser
    requirements:
        _locale: 'en|fr'

user_activate:
    path: /{_locale} /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'
